server:
  port: 8000
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

#配置数据源
spring:
  profiles:
    active: dev
  redis:
    #数据库索引
    database: ${REDIS_DB:1}
    host: ${REDIS_HOST:192.168.101.172}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PWD:}
    #连接超时时间
    timeout: 5000